[package]
name = "hexr"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.27"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
dirs = "5.0"

[[bin]]
name = "hexr"
path = "src/main.rs"
